### ISSUE TITLE
Support multiple contact groups

### ISSUE THREAD

**Issue by tiagoboldt** [DreamItGetIT/statuscake#21]
Current StatusCake configuration only supports one contact_id. Statuscake has updated their API to accept a list of contact IDs provided as a string, separating each contact ID with a comma. The library should update accordingly.

Documentation at: https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md

**Comment by croman** [comment]
Thanks for the PR @tiagoboldt. The changes look good, but the tests are failing. Could you look into that?

**Comment by tiagoboldt** [comment]
Thanks @croman. Latest commit fixes the tests. Can you please review? Thanks.

**Comment by matschaffer** [comment]
@tiagoboldt looks like ContactID has gone back to being an integer with just the first contact group. Now there's a `ContactGroups` field with an array of all assigned group names/ids.

https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md also mentions being able to insert a comma separated list for `ContactGroup`, but looks like the response still only lists the first group.

![charles_4_2_1_-_session_1__](https://user-images.githubusercontent.com/690/34977927-dbdac358-fadf-11e7-99b4-a158c268bc2b.png)

**Comment by tiagoboldt** [comment]
Hey @matschaffer, just checked the docs and could's find that change. I still see `A contact group ID assoicated with account to use. Comma separation for multiple ID's.`. Could it have been reverted back!? They're not very transparent on API changes :(

**Comment by matschaffer** [comment]
That was my take on it. That they probably changed the field type initially, realized they’d made a breaking change, then rolled it back but all in the same api version/path.
