### ISSUE TITLE
SSL Check support

### ISSUE THREAD

**Issue by AppleMaster** [DreamItGetIT/statuscake#32]
Does this API client support the methods in the API for creating SSL checks? Upstream terraform provider for statuscake does not - so curious whether the blocker is here or there.

**Comment by croman** [comment]
We don't support this, but I think this could be added here. Unfortunately we don't plan to add this feature anytime soon. We happily accept PRs in case you have the time to look into this.

**Comment by warmfusion** [comment]
WIP from someone trying to add this feature;

https://github.com/DreamItGetIT/statuscake/pull/37

**Comment by gaetanfl** [comment]
@alexandrefre took my work and made it works in #42

**Comment by croman** [comment]
#42 was merged.
