### ISSUE TITLE
Support for contact groups

### ISSUE THREAD

**Issue by alexdej** [DreamItGetIT/statuscake#5]
Any plan to support contact groups? https://www.statuscake.com/api/Contact%20Groups/Add%20or%20Update%20Contact%20Group.md

**Comment by croman** [comment]
Currently we don't have plans to add additional features, but we welcome PRs if you want to have a go at this. @alexdej

**Comment by matschaffer** [comment]
Just took a look at the API docs and it seems like it might be pretty out of date with the statuscake UI as well.

```
Field Value	Required (on Insert)	Accepted Values	Description
GroupName	Yes	String	The internal Group Name
DesktopAlert	No	0 / 1	Set to 1 To Enable Desktop Alerts
Email	No	String	Comma Seperated List of Emails To Alert. (no whitespace)
Boxcar	No	String	A Boxcar API Key
Pushover	No	String	A Pushover Account Key
PingURL	No	String	A URL To Send a POST alert.
Mobile	No	String	Comma Seperated List of International Format Cell Numbers
ContactID	No	Int	Provide to Update a Contact Group Rather Than Insert New
```

The current UI centers around groups that then have many integrations where as the API is flat and doesn't have support for PagerDuty or Slack.
