### ISSUE TITLE
Creating an SSL test sometimes fails with a checkrate type mismatch

### ISSUE THREAD

**Issue by saj** [DreamItGetIT/statuscake#50]
So here's a weird one.

I received the following error when attempting to create a new StatusCake SSL test using this library:

```
json: cannot unmarshal number into Go struct field createSsl.Input.checkrate of type string
```

Indeed, after I patched my local clone of this library to dump HTTP requests and responses, upstream was observed to send a `checkrate` as an integer type:

```
---- response dump:
dump error: <nil>
HTTP/2.0 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5562eac079f8ca53-YUL
Content-Type: application/json
Date: Thu, 16 Jan 2020 20:42:37 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: cloudflare
Set-Cookie: REDACTED
Set-Cookie: REDACTED
X-Powered-By: PHP/5.6.26
X-Turbo-Charged-By: LiteSpeed

{"Success":true,"Message":165652,"Input":{"domain":"https:\/\/www.google.com\/","checkrate":86400,"contact_groups":"","alert_reminder":true,"alert_expiry":true,"alert_broken":true,"alert_mixed":false,"alert_at":"1,7,14"}}
```

Note this bit in particular:

```
"checkrate":86400
```

This was especially curious because I could not, at first, reproduce that behaviour with a simple user agent:

```
curl -Ssv \
  -H 'Accept: application/json' \
  -H 'Username: REDACTED' \
  -H 'API: REDACTED' \
  -X PUT \
  -d 'domain=https://www.google.com/' \
  -d 'checkrate=86400' \
  -d 'contact_groups=' \
  -d 'alert_at=1,2,3' \
  -d 'alert_expiry=false' \
  -d 'alert_reminder=false' \
  -d 'alert_broken=false' \
  -d 'alert_mixed=false' \
  'https://app.statuscake.com/API/SSL/Update' \
  | tee /tmp/checkrate-86400.json \
  | jq .
```

Response:

``` json
{
  "Success": true,
  "Message": 165653,
  "Input": {
    "domain": "https://www.google.com/",
    "checkrate": "86400",
    "contact_groups": "",
    "alert_reminder": false,
    "alert_expiry": false,
    "alert_broken": false,
    "alert_mixed": false,
    "alert_at": "1,2,3"
  }
}
```

Here, `checkrate` is a **string**, which is what this library expects.

It wasn't until some time later that I realised I was specifying different `checkrate` values in my requests.  My test with curl used a `checkrate` of 86400, whereas my test with this library used a `checkrate` of 300.

Sure enough:

```
curl -Ssv \
  -H 'Accept: application/json' \
  -H 'Username: REDACTED' \
  -H 'API: REDACTED' \
  -X PUT \
  -d 'domain=https://www.google.com/' \
  -d 'checkrate=300' \
  -d 'contact_groups=' \
  -d 'alert_at=1,2,3' \
  -d 'alert_expiry=false' \
  -d 'alert_reminder=false' \
  -d 'alert_broken=false' \
  -d 'alert_mixed=false' \
  'https://app.statuscake.com/API/SSL/Update' \
  | tee /tmp/checkrate-300.json \
  | jq .
```

Response:

``` json
{
  "Success": true,
  "Message": 165654,
  "Input": {
    "domain": "https://www.google.com/",
    "checkrate": 86400,
    "contact_groups": "",
    "alert_reminder": false,
    "alert_expiry": false,
    "alert_broken": false,
    "alert_mixed": false,
    "alert_at": "1,2,3"
  }
}
```

Here, `checkrate` is an **integer**.

I have no words.

I know this library is not to blame, but would it make sense to flick `createSsl.Checkrate` over to the `interface{}` type and perform a conditional conversion to an intermediate `int` or `string` value at runtime?  (And presumably `updateSsl.Checkrate`, too.)

Lest someone else in my position stumble upon this bug in the future, here's a summary of just _some_ of the things that are entirely inaccurate in upstream's API documentation:

- 300 is documented as a valid `checkrate` parameter value.  In practice, that particular value will be silently discarded and substituted with another.  (Unless, presumably, you are on the highest-tier StatusCake plan.)
- The create operation is documented to respond with an integer-type `checkrate` value, but, as noted above, it is _usually_ a string-type value in practice.
- The update operation is documented to respond with an `Input` key.  In practice, that key is nowhere to be found.  Oh, and the `Message` value does not behave as documented, either.  There is no resource ID in the response whatsoever.
- The list operation is not documented to respond with a `checkrate` value.  In practice, the response will include an integer-type `checkrate` value.

Wayback links to upstream documentation - captured today:

- [List SSL tests](https://web.archive.org/web/20200116181356/https://www.statuscake.com/api/SSL/List%20SSL%20Tests.md)
- [Create SSL test](https://web.archive.org/web/20200116181306/https://www.statuscake.com/api/SSL/Create%20SSL%20Test.md)
- [Update SSL test](https://web.archive.org/web/20200116181333/https://www.statuscake.com/api/SSL/Update%20SSL%20Test.md)

**Comment by croman** [comment]
I think there are similar type or name inconsistencies in the StatusCake API with other fields as well.

As long as the inconsistency remains, changing the type to `interface{}` makes sense. My only concern is to find a way to avoid breaking libraries that use this one.

If you have the time to submit a PR I'll be happy to have a look.
